plugins {
    id "com.android.application"
}

android {
    namespace "cn.mitebo.iot"
    compileSdk 35

    defaultConfig {
        applicationId "cn.mitebo.iot"
        minSdk 23
        targetSdk 35
        versionCode 84
        versionName "1.0.84"
    }
}

tasks.withType(JavaCompile).configureEach {
    options.fork = false
}
